# Site settings
title: Areidz
header-img: img/home-bg-1.jpg
email: areidz@areidz.me
description: "Thoughts, ROM Hacking, Reverse Engineering and everything related."
baseurl: ""
url: "http://areidz.me"
twitter_username: Areidz
github_username:  Areidz

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
